### ISSUE TITLE
第一項の加算

### ISSUE THREAD

**Issue by moridora** [Yseitaro/git-training-2022610#1]
## 操作手順
* -2 + -2と入力したら
* 0になった

## 本来の想定
* -2 + -2と入力したら
* -4になってほしい

## 操作環境
* OS：Mac OS 
* OSバージョン：11
* ブラウザ：Chrome
* ブラウザバージョン：102.0.5005.61（Official Build） （arm64）

**Comment by MiyamotoRin** [comment]
解けた
